USE [master]
GO

/****** Object:  Database [DigiturkApi]    Script Date: 7.08.2020 21:40:25 ******/
CREATE DATABASE [DigiturkApi]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DigiturkApi', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\DigiturkApi.mdf' , SIZE = 4288KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'DigiturkApi_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\DigiturkApi_log.ldf' , SIZE = 1072KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [DigiturkApi] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DigiturkApi].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DigiturkApi] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DigiturkApi] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DigiturkApi] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DigiturkApi] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DigiturkApi] SET ARITHABORT OFF 
GO

ALTER DATABASE [DigiturkApi] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [DigiturkApi] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DigiturkApi] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DigiturkApi] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DigiturkApi] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DigiturkApi] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DigiturkApi] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DigiturkApi] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DigiturkApi] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DigiturkApi] SET  ENABLE_BROKER 
GO

ALTER DATABASE [DigiturkApi] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DigiturkApi] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DigiturkApi] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DigiturkApi] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DigiturkApi] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DigiturkApi] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [DigiturkApi] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DigiturkApi] SET RECOVERY FULL 
GO

ALTER DATABASE [DigiturkApi] SET  MULTI_USER 
GO

ALTER DATABASE [DigiturkApi] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DigiturkApi] SET DB_CHAINING OFF 
GO

ALTER DATABASE [DigiturkApi] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [DigiturkApi] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [DigiturkApi] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [DigiturkApi] SET  READ_WRITE 
GO

